### ISSUE TITLE
大佬, lockman可以更新下吗, 系统更新到ios17后用不了了

### ISSUE THREAD

**Issue by hehuapei** [qhd/AASubviews#2]

**Comment by qhd** [comment]
@hehuapei 具体是什么问题

**Comment by hehuapei** [comment]
> @hehuapei 具体是什么问题

17.4系统, 选锁屏组件的时候直接没有出现lockman, 选不了了

**Comment by qhd** [comment]
> > @hehuapei 具体是什么问题
> 
> 17.4系统, 选锁屏组件的时候直接没有出现lockman, 选不了了

我刚试了一下，没问题😳

**Comment by hehuapei** [comment]
> > > @hehuapei 具体是什么问题
> > 
> > 
> > 17.4系统, 选锁屏组件的时候直接没有出现lockman, 选不了了
> 
> 我刚试了一下，没问题😳

卸了重新安装后, 可以了, 打扰了大佬, 工具很好用!
